name: json_parser
description: A JSON parser with auto object mapping for Flutter using reflection.
version: 0.1.2
author: Giovanni Terlingen <me@giovanniterlingen.com>
homepage: https://github.com/gi097/json_parser

environment:
    sdk: ">=1.19.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  reflectable: 2.0.2
  build_runner: 0.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
